# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestStudentprofile():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_studentprofile(self):
    self.driver.get("http://127.0.0.1:8000/dashboard/")
    self.driver.set_window_size(1536, 816)
    self.driver.find_element(By.ID, "id_first_name").click()
    self.driver.find_element(By.ID, "id_first_name").send_keys("admin1")
    self.driver.find_element(By.ID, "id_last_name").click()
    self.driver.find_element(By.ID, "id_last_name").send_keys("admin")
    self.driver.find_element(By.ID, "id_contact_number").click()
    self.driver.find_element(By.ID, "id_contact_number").send_keys("2345678901")
    self.driver.find_element(By.ID, "menu-toggle").click()
    self.driver.find_element(By.ID, "menu-toggle").click()
    self.driver.find_element(By.CSS_SELECTOR, ".list-group-item:nth-child(2)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".m-2").click()
  
