# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestStudentprofilefeatures():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_studentprofilefeatures(self):
    self.driver.get("http://127.0.0.1:8000/dashboard/")
    self.driver.set_window_size(1536, 816)
    self.driver.find_element(By.LINK_TEXT, "Password Reset").click()
    self.driver.find_element(By.ID, "id_old_password").send_keys("admin")
    self.driver.find_element(By.ID, "id_new_password1").click()
    self.driver.find_element(By.ID, "id_new_password1").send_keys("1a234567")
    self.driver.find_element(By.ID, "id_new_password2").click()
    self.driver.find_element(By.ID, "id_new_password2").send_keys("1a234567")
    self.driver.find_element(By.CSS_SELECTOR, ".btn-outline-info").click()
    self.driver.find_element(By.ID, "menu-toggle").click()
    self.driver.find_element(By.ID, "menu-toggle").click()
    self.driver.find_element(By.LINK_TEXT, "Add Complaints").click()
    self.driver.find_element(By.ID, "id_Subject").click()
    self.driver.find_element(By.ID, "id_Subject").send_keys("fan issues")
    self.driver.find_element(By.ID, "id_Type_of_complaint").click()
    dropdown = self.driver.find_element(By.ID, "id_Type_of_complaint")
    dropdown.find_element(By.XPATH, "//option[. = 'Hostel']").click()
    self.driver.find_element(By.ID, "id_Description").click()
    self.driver.find_element(By.ID, "id_Description").send_keys("The fan is still broken and causing issues in day-to-day tasks")
    self.driver.find_element(By.CSS_SELECTOR, ".btn:nth-child(5)").click()
    self.driver.find_element(By.LINK_TEXT, "UnSolved Complaints").click()
    self.driver.find_element(By.LINK_TEXT, "Solved Complaints").click()
    self.driver.find_element(By.LINK_TEXT, "UnSolved Complaints").click()
    self.driver.find_element(By.CSS_SELECTOR, "tbody:nth-child(2) .btn").click()
    self.driver.find_element(By.LINK_TEXT, "Home").click()
    self.driver.find_element(By.LINK_TEXT, "Logout").click()
  
